/** Home screen–specific layout tokens (does not affect Welcome). */

export const PrikinHomeLayout = {
  /** Shared horizontal gutter for header, greeting, cards, community. */
  contentHorizontalPadding: 14,
  logoWidth: 96,
  logoBottomGap: 2,
  logoToLocationGap: 4,
  headerWeatherBlockGap: 2,
  headerLeftColumnFlex: 0.56,
  headerRightColumnFlex: 0.44,
  dayMessageWidth: 138,
  greetingTopPadding: 0,
  greetingBottomPadding: 0,
  sectionGap: 6,
  cardStackGap: 6,
  communitySectionTopGap: 4,
  cardRadius: 16,
  cardPaddingHorizontal: 14,
  cardPaddingVertical: 6,
  cardInnerGap: 6,
  cardTitleToContentGap: 1,
  cardTitleToButtonGap: 4,
  locationFontSize: 15,
  locationLineHeight: 20,
  temperatureFontSize: 26,
  temperatureLineHeight: 30,
  feelsLikeFontSize: 12,
  feelsLikeLineHeight: 16,
  greetingFontSize: 22,
  greetingLineHeight: 26,
  sectionCardTitleFontSize: 21,
  sectionCardTitleLineHeight: 25,
  cardMessageFontSize: 17,
  cardMessageLineHeight: 22,
  cardBodyFontSize: 15,
  cardBodyLineHeight: 20,
  cardCopyInnerGap: 3,
  wornSectionTitleFontSize: 21,
  wornSectionBodyFontSize: 15,
  wornSectionTitleBodyGap: 4,
  wornEmptyTextMaxWidthRatio: 0.78,
  wornEmptyAccentWidth: 44,
  todayCardRowGap: 8,
  outfitIllustrationWidth: 126,
  outfitIllustrationAspectRatio: 190 / 180,
  firstItemCardRowGap: 8,
  hangerIllustrationWidth: 102,
  hangerIllustrationAspectRatio: 180 / 190,
  homePrimaryButtonMinHeight: 42,
  homePrimaryButtonPaddingVertical: 8,
  homePrimaryButtonLabelFontSize: 15,
  homePrimaryButtonLabelLineHeight: 19,
  homePrimaryButtonIconSize: 18,
  homePrimaryButtonRadius: 22,
} as const;
