/** Home screen–specific layout tokens (does not affect Welcome). */

export const PrikinHomeLayout = {
  logoWidth: 96,
  logoToLocationGap: 6,
  sectionGap: 8,
  cardRadius: 16,
  cardPaddingHorizontal: 16,
  cardPaddingVertical: 8,
  cardInnerGap: 6,
  cardTitleToContentGap: 2,
  headerLeftColumnFlex: 0.56,
  headerRightColumnFlex: 0.44,
  dayMessageWidth: 138,
  locationFontSize: 15,
  locationLineHeight: 20,
  temperatureFontSize: 26,
  temperatureLineHeight: 30,
  feelsLikeFontSize: 12,
  feelsLikeLineHeight: 16,
  greetingFontSize: 22,
  greetingLineHeight: 26,
  sectionCardTitleFontSize: 21,
  sectionCardTitleLineHeight: 25,
  cardMessageFontSize: 17,
  cardMessageLineHeight: 22,
  cardBodyFontSize: 15,
  cardBodyLineHeight: 20,
  wornSectionTitleFontSize: 21,
  wornSectionBodyFontSize: 15,
  outfitIllustrationWidth: 108,
  outfitIllustrationAspectRatio: 190 / 180,
  hangerIllustrationWidth: 96,
  hangerIllustrationAspectRatio: 180 / 190,
} as const;
