/** Home screen–specific layout tokens (does not affect Welcome). */

export const PrikinHomeLayout = {
  logoWidth: 125,
  logoToLocationGap: 8,
  sectionGap: 10,
  cardRadius: 16,
  cardPaddingHorizontal: 16,
  cardPaddingVertical: 10,
  cardInnerGap: 6,
  cardTitleToContentGap: 4,
  locationFontSize: 15,
  locationLineHeight: 20,
  temperatureFontSize: 26,
  temperatureLineHeight: 30,
  feelsLikeFontSize: 12,
  feelsLikeLineHeight: 16,
  greetingFontSize: 21,
  greetingLineHeight: 25,
  cardHeadingFontSize: 19,
  cardHeadingLineHeight: 24,
  firstItemCardHeadingFontSize: 18,
  firstItemCardHeadingLineHeight: 22,
  cardMessageFontSize: 16,
  cardMessageLineHeight: 21,
  cardBodyFontSize: 14,
  cardBodyLineHeight: 19,
  wornSectionTitleFontSize: 18,
  wornSectionBodyFontSize: 14,
  outfitIllustrationWidth: 210,
  outfitIllustrationContentScale: 1.14,
  hangerIllustrationWidth: 118,
} as const;
